services:
  quant_app:
    build: .
    container_name: quant_web_app
    restart: always
    env_file: .env
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8000:8000"
    volumes:
      - ./backend/database:/app/backend/database
      - ./logs:/app/logs
